name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npm run cy:run

    - name: Generate Cypress Test Report
      run: |
        mkdir -p testResults
        npx cypress run --reporter mochawesome --reporter-options reportDir=testResults,overwrite=false,html=false,json=true

    - name: Upload Cypress Test Report
      uses: actions/upload-artifact@v2
      with:
        name: cypress-test-report
        path: testResults/
